// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaMq17yPtXRshqksV7bX7syS_ira-8AnU',
    appId: '1:1096293231216:android:25bd5c11aeca868c1fe2b5',
    messagingSenderId: '1096293231216',
    projectId: 'taskify-ccee9',
    storageBucket: 'taskify-ccee9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0aTM1v0IqR9wySSCBr8SceMG683SFZwQ',
    appId: '1:1096293231216:ios:c757e056fb6e8f5b1fe2b5',
    messagingSenderId: '1096293231216',
    projectId: 'taskify-ccee9',
    storageBucket: 'taskify-ccee9.appspot.com',
    androidClientId: '1096293231216-lftkl76stmhk2pseeufsuqo9tlte2vnt.apps.googleusercontent.com',
    iosClientId: '1096293231216-o63fur6vo814o109cjeqs5j2m50errhf.apps.googleusercontent.com',
    iosBundleId: 'com.app.taskify',
  );

}